; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; upload data via platformio icon, then "Upload Filesystem image"

[platformio]
default_envs = ttgo-t1_DMD

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_port = /dev/cu.usbserial*
monitor_filters = esp32_exception_decoder
upload_speed = 921600

lib_deps =
  SPI
  bodmer/TFT_eSPI@^2.5.34
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git#v1.4
  ArduinoJson
  AsyncTCP
  https://github.com/me-no-dev/ESPAsyncWebServer.git  
  https://github.com/emilv/ArduinoSort.git

build_flags = 
    !python /Users/thomas/Documents/PlatformIO/Projects/wifisetting.py

[env:ttgo-t1_DMD]
board = ttgo-t1
board_build.mcu = esp32
build_flags = 
  ${env.build_flags}
    '-DUseDMD=true'
;    '-Dwebdebug=1'    

lib_deps =
    https://github.com/moononournation/Arduino_GFX
    adafruit/Adafruit GFX Library
    https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA
    

upload_protocol = espota
upload_port = 192.168.0.40   
; // 135   ;  43 oben /dev/cu.usbserial*   -- 40 unten
;upload_speed = 460800
 
  

[env:esp32dev_TFT]

lib_deps =
    SPIFFS

    
;upload_port = /dev/cu.wch*
;upload_protocol = espota
;upload_port = 192.168.0.140   ;   /dev/cu.usbserial*
;upload_speed = 460800

build_flags =  
  ${env.build_flags}
    '-DUSER_SETUP_LOADED'
    '-DILI9488_DRIVER'
    '-DTFT_MISO=19' 
    '-DTFT_MOSI=23'
    '-DTFT_SCLK=18'
    '-DTFT_CS=22'
    '-DTFT_DC=2'
    '-DTFT_RST=4'
    '-DTOUCH_CS=-1'
    '-DLOAD_GLCD'
    '-DSPI_FREQUENCY=27000000'
    '-DSPI_READ_FREQUENCY=16000000'
    '-DSPI_TOUCH_FREQUENCY=2500000'
    '-Dwebdebug=1'


[env:cyd]
build_flags =
   ${env.build_flags}
  -DLV_CONF_SKIP
  -DLV_USE_TFT_ESPI
	-DUSER_SETUP_LOADED
	-DUSE_HSPI_PORT
	-DTFT_MISO=12
	-DTFT_MOSI=13
	-DTFT_SCLK=14
	-DTFT_CS=15
	-DTFT_DC=2
	-DTFT_RST=-1
	-DTFT_BL=21
	-DTFT_BACKLIGHT_ON=HIGH
	-DSPI_FREQUENCY=55000000
	-DSPI_READ_FREQUENCY=20000000
	-DSPI_TOUCH_FREQUENCY=2500000
	-DILI9341_2_DRIVER
    '-Dwebdebug=1'
    '-DUseCYD=1'
	-DLOAD_GLCD
	-DLOAD_FONT2
	-DLOAD_FONT4
	-DLOAD_FONT6
	-DLOAD_FONT7
	-DLOAD_FONT8
	-DLOAD_GFXFF

[env:cyd2usb]

build_flags =
   ${env.build_flags}
  -DLV_CONF_SKIP
  -DLV_USE_TFT_ESPI
	-DUSER_SETUP_LOADED
	-DUSE_HSPI_PORT
	-DTFT_MISO=12
	-DTFT_MOSI=13
	-DTFT_SCLK=14
	-DTFT_CS=15
	-DTFT_DC=2
	-DTFT_RST=-1
	-DTFT_BL=21
	-DTFT_BACKLIGHT_ON=HIGH
	-DSPI_FREQUENCY=55000000
	-DSPI_READ_FREQUENCY=20000000
	-DSPI_TOUCH_FREQUENCY=2500000
    -DST7789_DRIVER
	-DTFT_INVERSION_OFF
  -DTFT_RGB_ORDER=TFT_BGR
    '-Dwebdebug=1'
    '-DUseCYD=1'
	-DLOAD_GLCD
	-DLOAD_FONT2
	-DLOAD_FONT4
	-DLOAD_FONT6
	-DLOAD_FONT7
	-DLOAD_FONT8
	-DLOAD_GFXFF